name:                myproject
version:             1.0.0.0
author:              Author name here
maintainer:          example@example.com
copyright:           "MIT"

dependencies:
  - base
  - mtl
  - JuicyPixels
executables:
  main:
    main: src/Main.hs
    # dependencies: [base, my-lib]
    ghc-options: [-threaded]

library:
  source-dirs: src
